<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSizeColorsTableSeeder extends Seeder
{

    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            //// váy đầm
                // //Sp1: Đầm a không tay
                //     [
                //         'id_color' => 3,
                //         'id_size' => 2,
                //         'id_product' => 'DE01014',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 3,
                //         'id_size' => 3,
                //         'id_product' => 'DE01014',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 3,
                //         'id_size' => 4,
                //         'id_product' => 'DE01014',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 2,
                //         'id_product' => 'DE01014',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 3,
                //         'id_product' => 'DE01014',
                //         'stock'=>7,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 4,
                //         'id_product' => 'DE01014',
                //         'stock'=>3,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],

                // //Sp2: Đầm đuôi cá tay lỡ
                //     [
                //         'id_color' => 1,
                //         'id_size' => 2,
                //         'id_product' => 'DE01016',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 1,
                //         'id_size' => 3,
                //         'id_product' => 'DE01016',
                //         'stock'=>8,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 1,
                //         'id_size' => 4,
                //         'id_product' => 'DE01016',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 1,
                //         'id_size' => 5,
                //         'id_product' => 'DE01016',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],

                // //Sp3: Đầm suông bâu danton
                //     [
                //         'id_color' => 7,
                //         'id_size' => 2,
                //         'id_product' => 'DE01062',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 3,
                //         'id_product' => 'DE01062',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 4,
                //         'id_product' => 'DE01062',
                //         'stock'=>9,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 8,
                //         'id_size' => 2,
                //         'id_product' => 'DE01062',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 8,
                //         'id_size' => 3,
                //         'id_product' => 'DE01062',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 8,
                //         'id_size' => 4,
                //         'id_product' => 'DE01062',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                // //Sp4: Đầm A xòe xếp ly
                //     [
                //         'id_color' => 7,
                //         'id_size' => 2,
                //         'id_product' => 'DE01035',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 3,
                //         'id_product' => 'DE01035',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 4,
                //         'id_product' => 'DE01035',
                //         'stock'=>6,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                // //sp5: Đầm bút chì phối ren
                //     [
                //         'id_color' => 6,
                //         'id_size' => 2,
                //         'id_product' => 'DE01075',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 3,
                //         'id_product' => 'DE01075',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 4,
                //         'id_product' => 'DE01075',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                // //sp6: Đầm phối bèo rã tầng
                //     [
                //         'id_color' => 6,
                //         'id_size' => 2,
                //         'id_product' => 'DE01015',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 3,
                //         'id_product' => 'DE01015',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 4,
                //         'id_product' => 'DE01015',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                // //sp7: đầm a cổ yếm
                //     [
                //         'id_color' => 1,
                //         'id_size' => 2,
                //         'id_product' => 'DE01037',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 1,
                //         'id_size' => 3,
                //         'id_product' => 'DE01037',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 1,
                //         'id_size' => 4,
                //         'id_product' => 'DE01037',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 1,
                //         'id_size' => 5,
                //         'id_product' => 'DE01037',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                // //sp8: Đầm sơ mi nắp túi
                //     [
                //         'id_color' => 7,
                //         'id_size' => 1,
                //         'id_product' => 'DD12043',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 2,
                //         'id_product' => 'DD12043',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 3,
                //         'id_product' => 'DD12043',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 4,
                //         'id_product' => 'DD12043',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 7,
                //         'id_size' => 5,
                //         'id_product' => 'DD12043',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                // //sp9: Đầm xòe tay bí
                //     [
                //         'id_color' => 6,
                //         'id_size' => 2,
                //         'id_product' => 'DD12093',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 3,
                //         'id_product' => 'DD12093',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 4,
                //         'id_product' => 'DD12093',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 3,
                //         'id_size' => 2,
                //         'id_product' => 'DD12093',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 3,
                //         'id_size' => 3,
                //         'id_product' => 'DD12093',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 3,
                //         'id_size' => 4,
                //         'id_product' => 'DD12093',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                // //sp10: Đầm tơ đính nút
                // [
                //     'id_color' => 2,
                //     'id_size' => 2,
                //     'id_product' => 'DD12039',
                //     'stock'=>10,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // [
                //     'id_color' => 2,
                //     'id_size' => 3,
                //     'id_product' => 'DD12039',
                //     'stock'=>10,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // [
                //     'id_color' => 2,
                //     'id_size' => 4,
                //     'id_product' => 'DD12039',
                //     'stock'=>0,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // [
                //     'id_color' => 3,
                //     'id_size' => 2,
                //     'id_product' => 'DD12039',
                //     'stock'=>0,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // [
                //     'id_color' => 3,
                //     'id_size' => 3,
                //     'id_product' => 'DD12039',
                //     'stock'=>10,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // [
                //     'id_color' => 3,
                //     'id_size' => 4,
                //     'id_product' => 'DD12039',
                //     'stock'=>0,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // //sp11: Đầmtơ rã tầng
                // [
                //     'id_color' => 6,
                //     'id_size' => 2,
                //     'id_product' => 'DD12042',
                //     'stock'=>10,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // [
                //     'id_color' => 6,
                //     'id_size' => 3,
                //     'id_product' => 'DD12042',
                //     'stock'=>10,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // [
                //     'id_color' => 6,
                //     'id_size' => 4,
                //     'id_product' => 'DD12042',
                //     'stock'=>10,
                //     'created_at' => $now,
                //     'updated_at' => $now,
                // ],
                // //sp12: Đầm linen cổ danton
                //     [
                //         'id_color' => 6,
                //         'id_size' => 2,
                //         'id_product' => 'LDD1207',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 3,
                //         'id_product' => 'LDD1207',
                //         'stock'=>10,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                //     [
                //         'id_color' => 6,
                //         'id_size' => 4,
                //         'id_product' => 'LDD1207',
                //         'stock'=>0,
                //         'created_at' => $now,
                //         'updated_at' => $now,
                //     ],
                
            //// thời trang
                //sp1: quần tây ống suông: 
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 2,
                    //     'id_product' => 'QE01042',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 3,
                    //     'id_product' => 'QE01042',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 4,
                    //     'id_product' => 'QE01042',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 5,
                    //     'id_product' => 'QE01042',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp2: Chân váy xòe đính nút
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 2,
                    //     'id_product' => 'VE01081',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 3,
                    //     'id_product' => 'VE01081',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 4,
                    //     'id_product' => 'VE01081',
                    //     'stock'=>01,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 5,
                    //     'id_product' => 'VE01081',
                    //     'stock'=>02,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp3: Áo sơ mi tay dập ly
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 2,
                    //     'id_product' => 'AE01010',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 3,
                    //     'id_product' => 'AE01010',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 4,
                    //     'id_product' => 'AE01010',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp4: Quần tây sọc ống suông
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 1,
                    //     'id_product' => 'QE01023',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 2,
                    //     'id_product' => 'QE01023',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 3,
                    //     'id_product' => 'QE01023',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 4,
                    //     'id_product' => 'QE01023',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 5,
                    //     'id_product' => 'QE01023',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp5: Áo 2 dây thun B1
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 2,
                    //     'id_product' => 'BATE00009',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 3,
                    //     'id_product' => 'BATE00009',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 4,
                    //     'id_product' => 'BATE00009',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 2,
                    //     'id_product' => 'BATE00009',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 3,
                    //     'id_product' => 'BATE00009',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 4,
                    //     'id_product' => 'BATE00009',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp6: Áo sơ mi cơ bản
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 1,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 2,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 3,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 4,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 5,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 1,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 2,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 3,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 4,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 7,
                    //     'id_size' => 5,
                    //     'id_product' => 'AE01013',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp7: Quần giả váy lưng liền
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 2,
                    //     'id_product' => 'SHE01040',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 3,
                    //     'id_product' => 'SHE01040',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 4,
                    //     'id_product' => 'SHE01040',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],

                //sp8: Blazer lửng bâu tròn
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 2,
                    //     'id_product' => 'OWE01085',
                    //     'stock'=>8,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 3,
                    //     'id_product' => 'OWE01085',
                    //     'stock'=>9,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 6,
                    //     'id_size' => 4,
                    //     'id_product' => 'OWE01085',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp9: Chân váy túi đắp
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 2,
                    //     'id_product' => 'VE01020',
                    //     'stock'=>8,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 3,
                    //     'id_product' => 'VE01020',
                    //     'stock'=>9,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 4,
                    //     'id_product' => 'VE01020',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 3,
                    //     'id_size' => 2,
                    //     'id_product' => 'VE01020',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 3,
                    //     'id_size' => 3,
                    //     'id_product' => 'VE01020',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 3,
                    //     'id_size' => 4,
                    //     'id_product' => 'VE01020',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp10: Quần tây ống loe
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 1,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 2,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 3,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 4,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 5,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 1,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 2,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 3,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 4,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 5,
                    //     'id_size' => 5,
                    //     'id_product' => 'QE01084',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp11: Quần ống đứng túi xéo
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 1,
                    //     'id_product' => 'QE01044',
                    //     'stock'=>0,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 2,
                    //     'id_product' => 'QE01044',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 3,
                    //     'id_product' => 'QE01044',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 4,
                    //     'id_product' => 'QE01044',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 5,
                    //     'id_product' => 'QE01044',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                //sp12: Chân váy đuôi cá
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 2,
                    //     'id_product' => 'VE01069',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 3,
                    //     'id_product' => 'VE01069',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 4,
                    //     'id_product' => 'VE01069',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
                    // [
                    //     'id_color' => 1,
                    //     'id_size' => 5,
                    //     'id_product' => 'VE01069',
                    //     'stock'=>10,
                    //     'created_at' => $now,
                    //     'updated_at' => $now,
                    // ],
            ];

        DB::table('product_size_colors')->insert($data);
    }
}
